[rabbitmq]
# 基础连接配置
host = "127.0.0.1"
port = 5672
vhost = "/"
username = "star"
password = "Juiqo37y5"
max_retries = 3
retry_delay_ms = 1000

# 改为队列配置列表
[[rabbitmq.queues]]
name = "cruise.sync.queue"
alias = "巡游轨迹同步队列"
timeout_ms = 5000  # 可选的超时设置

[[rabbitmq.queues]]
name = "online.order.sync.queue"
alias = "网约订单同步队列"
timeout_ms = 5000  # 可选的超时设置

[[rabbitmq.queues]]
name = "online.gps.sync.queue"
alias = "网约轨迹同步队列"

[[rabbitmq.queues]]
name = "passAndDanger.gps.sync.queue"
alias = "危险品轨迹同步队列"

[[rabbitmq.queues]]
name = "vehicle.gps.sync.queue"
alias = "车辆轨迹同步队列"
