[rabbitmq]
# 基础连接配置
host = "127.0.0.1"
port = 5672
vhost = "/"
username = "star"
password = "Juiqo37y5"
max_retries = 3
retry_delay_ms = 1000

# 改为队列配置列表
[[rabbitmq.queues]]
name = "cruise.sync.queue"
alias = "巡游轨迹同步队列"
timeout_ms = 5000  # 可选的超时设置

[[rabbitmq.queues]]
name = "online.order.sync.queue"
alias = "网约订单同步队列"
timeout_ms = 5000  # 可选的超时设置

[[rabbitmq.queues]]
name = "online.gps.sync.queue"
alias = "网约轨迹同步队列"

[[rabbitmq.queues]]
name = "passAndDanger.gps.sync.queue"
alias = "危险品轨迹同步队列"

[[rabbitmq.queues]]
name = "vehicle.gps.sync.queue"
alias = "车辆轨迹同步队列"

[dingtalk]
# 钉钉机器人配置
webhook_url = "https://oapi.dingtalk.com/robot/send?sign={}&timestamp={}"
secret = "SEC01fda2a7e306e40342d6d9208070229ab695fc58261cf06a7acaff15b4d83dcc"
user_id = "Monitor"
custom_robot_token = "f75bc7df728e57bb061e84d2e003cb3fe349044f33d9396a24be8f3a6f52ea4a"