[rabbitmq]
# 基础连接配置
host = "127.0.0.1"
port = 5672
vhost = "/"
username = "star"
password = "Juiqo37y5"
max_retries = 3
retry_delay_ms = 1000

# 改为队列配置列表
[[rabbitmq.queues]]
name = "cruise.sync.queue"
alias = "巡游轨迹同步队列"
timeout_ms = 5000  # 可选的超时设置

[[rabbitmq.queues]]
name = "online.order.sync.queue"
alias = "网约订单同步队列"
timeout_ms = 5000  # 可选的超时设置

[[rabbitmq.queues]]
name = "online.gps.sync.queue"
alias = "网约轨迹同步队列"

[[rabbitmq.queues]]
name = "passAndDanger.gps.sync.queue"
alias = "危险品轨迹同步队列"

[[rabbitmq.queues]]
name = "vehicle.gps.sync.queue"
alias = "车辆轨迹同步队列"

[rabbitmq.warning]
enabled = true  # 是否启用RabbitMQ告警
warning_queue_size = 100000
warning_type = "DingTalk"  # 告警方式，目前仅支持钉钉

[oracle]
username = "ADMIN_PLATFORM"
password = "Hauasdkjnq#318!"
host = "127.0.0.1"
port = 62001
db_name = "orcl11g"

[dingtalk]
# 钉钉机器人配置
#webhook_url = "https://oapi.dingtalk.com/robot/send"
#secret = "SEC01fda2a7e306e40342d6d9208070229ab695fc58261cf06a7acaff15b4d83dcc"
#user_id = "Monitor"
#custom_robot_token = "f75bc7df728e57bb061e84d2e003cb3fe349044f33d9396a24be8f3a6f52ea4a"
webhook_url = "http://172.26.56.234:30001/robot/send"
secret = "SEC6e530b1562fd61cbb034080cf58f218ec6b3c1672663d105cddf3e347a1ee309"
user_id = "轨迹数据接收"
custom_robot_token = "c545703818d22c96c97008f3cdb14b86666cfe9087e75f1cf33386c93d9f804e"

[warning]
# 告警配置
warning_valid = false  # 是否启用告警功能
warning_type = "DingTalk"
warning_time_interval = 10  # 告警时间间隔，单位：分钟
